{
  "version": 2,
  "snapshot": {
    "widths": [375, 768, 1280],
    "minHeight": 1024,
    "percyCSS": ""
  },
  "discovery": {
    "allowedHostnames": ["localhost"],
    "networkIdleTimeout": 125
  }
}
